<a href="https://colab.research.google.com/github/Porinita-Hoque/Students-Performance-Prediction-Dataset/blob/main/Students%20Dropout%20and%20Success%20Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Mount to DRIVE

In [1]:
from google.colab import drive

In [2]:
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
csv_path = '/content/drive/MyDrive/ML Projects/Students Dropout and Success Prediction/Students Dropout and Success Prediction Dataset.csv'

#### Dataframe

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv(csv_path)

In [6]:
df.head(5)

Marital status  Application mode  Application order  Course  \
0               1                17                  5     171   
1               1                15                  1    9254   
2               1                 1                  5    9070   
3               1                17                  2    9773   
4               2                39                  1    8014   

   Daytime/evening attendance\t  Previous qualification  \
0                             1                       1   
1                             1                       1   
2                             1                       1   
3                             1                       1   
4                             0                       1   

   Previous qualification (grade)  Nacionality  Mother's qualification  \
0                           122.0            1                      19   
1                           160.0            1                       1   
2                           122.0            1                      37   
3                           122.0            1                      38   
4                           100.0            1                      37   

   Father's qualification  ...  Curricular units 2nd sem (credited)  \
0                      12  ...                                    0   
1                       3  ...                                    0   
2                      37  ...                                    0   
3                      37  ...                                    0   
4                      38  ...                                    0   

   Curricular units 2nd sem (enrolled)  \
0                                    0   
1                                    6   
2                                    6   
3                                    6   
4                                    6   

   Curricular units 2nd sem (evaluations)  \
0                                       0   
1                                       6   
2                                       0   
3                                      10   
4                                       6   

   Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)  \
0                                    0                          0.000000   
1                                    6                         13.666667   
2                                    0                          0.000000   
3                                    5                         12.400000   
4                                    6                         13.000000   

   Curricular units 2nd sem (without evaluations)  Unemployment rate  \
0                                               0               10.8   
1                                               0               13.9   
2                                               0               10.8   
3                                               0                9.4   
4                                               0               13.9   

   Inflation rate   GDP    Target  
0             1.4  1.74   Dropout  
1            -0.3  0.79  Graduate  
2             1.4  1.74   Dropout  
3            -0.8 -3.12  Graduate  
4            -0.3  0.79  Graduate  

[5 rows x 37 columns]

##### Correlation Analysis: Correlation between feature and target variable.

In [7]:
correlation_matrix = df.corr()

<ipython-input-7-68bbfff3c4eb>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  correlation_matrix = df.corr()


In [8]:
sorted_correlations = correlation_matrix.iloc[:, -1].abs().sort_values(ascending=False)

In [9]:
print(sorted_correlations)

GDP                                               1.000000
Unemployment rate                                 0.335178
Curricular units 1st sem (without evaluations)    0.144673
Father's occupation                               0.131767
Mother's occupation                               0.124268
Inflation rate                                    0.112295
Curricular units 1st sem (evaluations)            0.099761
Mother's qualification                            0.083657
Curricular units 2nd sem (without evaluations)    0.080292
Debtor                                            0.075050
Father's qualification                            0.071610
Curricular units 2nd sem (grade)                  0.071269
Age at enrollment                                 0.064678
Previous qualification                            0.064069
Displaced                                         0.062875
Curricular units 1st sem (grade)                  0.054801
Previous qualification (grade)                    0.0526

#### Preprocessing

In [10]:
labels = df.iloc[:,-1]

In [11]:
labels.shape

(4424,)

In [12]:
labels.head(5)

0     Dropout
1    Graduate
2     Dropout
3    Graduate
4    Graduate
Name: Target, dtype: object

In [13]:
features = df.iloc[:,:-1]

In [14]:
features.shape

(4424, 36)

In [15]:
features.head(5)

Marital status  Application mode  Application order  Course  \
0               1                17                  5     171   
1               1                15                  1    9254   
2               1                 1                  5    9070   
3               1                17                  2    9773   
4               2                39                  1    8014   

   Daytime/evening attendance\t  Previous qualification  \
0                             1                       1   
1                             1                       1   
2                             1                       1   
3                             1                       1   
4                             0                       1   

   Previous qualification (grade)  Nacionality  Mother's qualification  \
0                           122.0            1                      19   
1                           160.0            1                       1   
2                           122.0            1                      37   
3                           122.0            1                      38   
4                           100.0            1                      37   

   Father's qualification  ...  \
0                      12  ...   
1                       3  ...   
2                      37  ...   
3                      37  ...   
4                      38  ...   

   Curricular units 1st sem (without evaluations)  \
0                                               0   
1                                               0   
2                                               0   
3                                               0   
4                                               0   

   Curricular units 2nd sem (credited)  Curricular units 2nd sem (enrolled)  \
0                                    0                                    0   
1                                    0                                    6   
2                                    0                                    6   
3                                    0                                    6   
4                                    0                                    6   

   Curricular units 2nd sem (evaluations)  \
0                                       0   
1                                       6   
2                                       0   
3                                      10   
4                                       6   

   Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)  \
0                                    0                          0.000000   
1                                    6                         13.666667   
2                                    0                          0.000000   
3                                    5                         12.400000   
4                                    6                         13.000000   

   Curricular units 2nd sem (without evaluations)  Unemployment rate  \
0                                               0               10.8   
1                                               0               13.9   
2                                               0               10.8   
3                                               0                9.4   
4                                               0               13.9   

   Inflation rate   GDP  
0             1.4  1.74  
1            -0.3  0.79  
2             1.4  1.74  
3            -0.8 -3.12  
4            -0.3  0.79  

[5 rows x 36 columns]

In [16]:
import numpy as np

In [17]:
features_np = np.array(features)

#### Scaling

In [18]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [19]:
# ssc = StandardScaler()
# features_scaled = ssc.fit_transform(features_np)

mms = MinMaxScaler()
features_scaled = mms.fit_transform(features_np)

In [20]:
print(features_scaled)

[[0.         0.28571429 0.55555556 ... 0.37209302 0.48888889 0.7661823 ]
 [0.         0.25       0.11111111 ... 0.73255814 0.11111111 0.64068692]
 [0.         0.         0.55555556 ... 0.37209302 0.48888889 0.7661823 ]
 ...
 [0.         0.         0.11111111 ... 0.73255814 0.11111111 0.64068692]
 [0.         0.         0.11111111 ... 0.20930233 0.         0.12417437]
 [0.         0.16071429 0.11111111 ... 0.59302326 1.         0.31175694]]


##### Feature Selection

In [21]:
from sklearn.feature_selection import SelectKBest, chi2

In [22]:
selector = SelectKBest(score_func=chi2, k=15)

In [23]:
x_selected = selector.fit_transform(features_scaled, labels)

In [24]:
selected_indices = selector.get_support(indices=True)

In [25]:
col_list = []
for items in selected_indices :
  col_list.append(items)

In [26]:
col_list

[0, 1, 5, 13, 15, 16, 17, 18, 19, 24, 25, 29, 30, 31, 32]

##### Data Split

In [27]:
x = features_scaled[:, col_list]

In [28]:
y = labels

In [29]:
from sklearn.model_selection import train_test_split, KFold

In [30]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=0)
cv = KFold(n_splits=10, random_state=1, shuffle=True)

In [31]:
x_train.shape

(3539, 15)

In [32]:
x_test.shape

(885, 15)

In [33]:
y_train.shape

(3539,)

In [34]:
y_test.shape

(885,)

### Classification

#### KNN

In [35]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

np.random.seed(123)

import time
start_time_KNN = time.time()

modelKNN = KNeighborsClassifier(n_neighbors=5)
modelKNN.fit(x_train, y_train)

y_predKNN = modelKNN.predict(x_test)

accuracy_KNN = accuracy_score(y_test, y_predKNN)
precision_KNN = precision_score(y_test, y_predKNN, average='weighted')
recall_KNN = recall_score(y_test, y_predKNN, average='weighted')
f1_KNN = f1_score(y_test, y_predKNN, average='weighted')

end_time_KNN = time.time()
time_KNN = end_time_KNN - start_time_KNN

print('KNN - Accuracy  : %.2f' % (accuracy_KNN*100), '%')
print('KNN - F1-Score  : %.2f' % (f1_KNN*100), '%')
print('KNN - Recall    : %.2f' % (recall_KNN*100), '%')
print('KNN - Precision : %.2f' % (precision_KNN*100), '%')
print('KNN - Time Taken : %.2f' % time_KNN, 'seconds')

KNN - Accuracy  : 72.77 %
KNN - F1-Score  : 72.32 %
KNN - Recall    : 72.77 %
KNN - Precision : 71.94 %
KNN - Time Taken : 0.07 seconds


#### SVM

In [36]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

np.random.seed(123)

import time
start_time_SVM = time.time()

modelSVM_RBF = SVC(kernel = 'linear')
modelSVM_RBF.fit(x_train, y_train)

y_predSVM_RBF = modelSVM_RBF.predict(x_test)

accuracy_SVM = accuracy_score(y_test, y_predSVM_RBF)
precision_SVM = precision_score(y_test, y_predSVM_RBF, average='weighted')
recall_SVM = recall_score(y_test, y_predSVM_RBF, average='weighted')
f1_SVM = f1_score(y_test, y_predSVM_RBF, average='weighted')

end_time_SVM = time.time()
time_SVM = end_time_SVM - start_time_SVM

print('SVM - Accuracy  : %.2f' % (accuracy_SVM*100), '%')
print('SVM - F1-Score  : %.2f' % (f1_SVM*100), '%')
print('SVM - Recall    : %.2f' % (recall_SVM*100), '%')
print('SVM - Precision : %.2f' % (precision_SVM*100), '%')
print('SVM - Time Taken : %.2f' % time_SVM, 'seconds')

SVM - Accuracy  : 74.80 %
SVM - F1-Score  : 73.85 %
SVM - Recall    : 74.80 %
SVM - Precision : 73.90 %
SVM - Time Taken : 0.25 seconds


#### RFC

In [37]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

np.random.seed(123)

import time
start_time_RFC = time.time()

modelRFC = RandomForestClassifier(n_estimators = 100, criterion = 'entropy')
modelRFC.fit(x_train, y_train)

y_predRFC = modelRFC.predict(x_test)

accuracy_RFC = accuracy_score(y_test, y_predRFC)
precision_RFC = precision_score(y_test, y_predRFC, average='weighted')
recall_RFC = recall_score(y_test, y_predRFC, average='weighted')
f1_RFC = f1_score(y_test, y_predRFC, average='weighted')

end_time_RFC = time.time()
time_RFC = end_time_RFC - start_time_RFC

print('RFC - Accuracy  : %.2f' % (accuracy_RFC*100), '%')
print('RFC - F1-Score  : %.2f' % (precision_RFC*100), '%')
print('RFC - Recall    : %.2f' % (recall_RFC*100), '%')
print('RFC - Precision : %.2f' % (f1_RFC*100), '%')
print('RFC - Time Taken : %.2f' % time_RFC, 'seconds')

RFC - Accuracy  : 78.08 %
RFC - F1-Score  : 76.89 %
RFC - Recall    : 78.08 %
RFC - Precision : 76.81 %
RFC - Time Taken : 0.45 seconds


#### Hist GBC

In [38]:
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

np.random.seed(123)

import time
start_time_HGBC = time.time()

modelHGBC = HistGradientBoostingClassifier()
modelHGBC.fit(x_train, y_train)

y_predHGBC = modelHGBC.predict(x_test)

accuracy_HGBC = accuracy_score(y_test, y_predHGBC)
precision_HGBC = precision_score(y_test, y_predHGBC, average='weighted')
recall_HGBC = recall_score(y_test, y_predHGBC, average='weighted')
f1_HGBC = f1_score(y_test, y_predHGBC, average='weighted')

end_time_HGBC = time.time()
time_HGBC = end_time_HGBC - start_time_HGBC

print('HGBC - Accuracy  : %.2f' % (accuracy_HGBC*100), '%')
print('HGBC - F1-Score  : %.2f' % (f1_HGBC*100), '%')
print('HGBC - Recall    : %.2f' % (recall_HGBC*100), '%')
print('HGBC - Precision : %.2f' % (precision_HGBC*100), '%')
print('HGBC - Time Taken : %.2f' % time_HGBC, 'seconds')

HGBC - Accuracy  : 76.50 %
HGBC - F1-Score  : 75.84 %
HGBC - Recall    : 76.50 %
HGBC - Precision : 75.55 %
HGBC - Time Taken : 2.93 seconds


#### Light GBM

In [39]:
from lightgbm import LGBMClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score


np.random.seed(123)

import time
start_time_GBM = time.time()

modelGBM = LGBMClassifier()
modelGBM.fit(x_train, y_train)

y_pred_GBM = modelGBM.predict(x_test)

accuracy_GBM = accuracy_score(y_test, y_pred_GBM)
precision_GBM = precision_score(y_test, y_pred_GBM, average='weighted')
recall_GBM = recall_score(y_test, y_pred_GBM, average='weighted')
f1_GBM = f1_score(y_test, y_pred_GBM, average='weighted')

end_time_GBM = time.time()
time_GBM = end_time_GBM - start_time_GBM

print('Light-GBM - Accuracy  : %.2f' % (accuracy_GBM*100), '%')
print('Light-GBM - F1-Score  : %.2f' % (f1_GBM*100), '%')
print('Light-GBM - Recall    : %.2f' % (recall_GBM*100), '%')
print('Light-GBM - Precision : %.2f' % (precision_GBM*100), '%')
print('Light-GBM - Time Taken : %.2f' % time_GBM, 'seconds')

Light-GBM - Accuracy  : 76.84 %
Light-GBM - F1-Score  : 75.93 %
Light-GBM - Recall    : 76.84 %
Light-GBM - Precision : 75.61 %
Light-GBM - Time Taken : 0.25 seconds
